DROP TABLE addmoneytable;
DROP TABLE CAMPINGTABLE ;
DROP TABLE REVIEWTABLE ;
DROP TABLE loadmoneytable;
DROP TABLE ORDERTABLE ;
DROP TABLE BASKETTABLE ;
DROP TABLE PRODUCTTABLE ;
DROP TABLE MEMBERTABLE ;

DROP SEQUENCE seq_addmoney;
DROP SEQUENCE seq_loadmoney;
DROP SEQUENCE SEQ_CAMPINGAREA;
DROP SEQUENCE SEQ_ORDER;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_BASKET;