CREATE SEQUENCE SEQ_CampingArea;

CREATE TABLE CAMPINGTABLE
   (	IDX NUMBER(5,0) PRIMARY KEY, 
	NAME VARCHAR2(2000), 
	LATITUDE NUMBER(10,5), 
	LONGITUDE NUMBER(10,5), 
	ADDRESS VARCHAR2(2000), 
	TELL VARCHAR2(2000),
	imgName VARCHAR2(1000)
	);
	
SELECT * FROM campingTable;	

SELECT * FROM MEMBERTABLE;

SELECT IDX, NAME, LATITUDE, LONGITUDE, ADDRESS, TELL, imgName, ABS(LATITUDE-36.50)+ABS(LONGITUDE-127) AS DISTANCE 
FROM CAMPINGTABLE
WHERE (latitude BETWEEN (36.50 - 0.9) AND (36.5 + 0.9) )
					AND (LONGITUDE BETWEEN (127 - 1.1) AND (127 + 1.1) )
ORDER BY DISTANCE;

DROP SEQUENCE SEQ_CampingArea;
DROP TABLE CAMPINGTABLE;