INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(2, '부대찌개', 16000, 30, 'foodNum01');
INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(21, '삼겹살', 15000, 200, 'foodNum02');
INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(22, '오삼불고기', 13000, 200, 'foodNum03');
INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(23, '사천마라탕', 15000, 200, 'foodNum04');
INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(24, '우삼겹 된장찌개', 12000, 300, 'foodNum05');
INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(25, '부채살 스테이크', 17000, 200, 'foodNum06');
INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(26, '밀푀유나베', 15000, 200, 'foodNum07');
INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(27, '만두전골', 12000, 200, 'foodNum09');
INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(28, '감바스 알아히요', 14000, 200, 'foodNum08');
INSERT INTO TEST_PM.PRODUCTTABLE
(IDX, PRODUCTID, PRICE, STOCK, IMGNAME)
VALUES(1, 'bbq', 30000, 300, 'foodNum10');





SELECT * FROM PRODUCTTABLE p ;